const {
  GITHUB_API_BASE_URL,
  GITHUB_API_REPOS_PATH,
  GITHUB_API_ORGS_PATH,
  GITHUB_API_PAGE_QUERY,
  GITHUB_API_PER_PAGE_QUERY,
  GITHUB_API_TOKEN,
} = process.env;

const GITHUB_API_PER_PAGE_LIMIT = parseInt(
  process.env.GITHUB_API_PER_PAGE_LIMIT,
  10
);

module.exports = {
  apiBaseUrl: GITHUB_API_BASE_URL,
  apiOrgsPath: GITHUB_API_ORGS_PATH,
  apiReposPath: GITHUB_API_REPOS_PATH,
  apiPageQuery: GITHUB_API_PAGE_QUERY,
  apiPerPageQuery: GITHUB_API_PER_PAGE_QUERY,
  apiPerPageLimit: GITHUB_API_PER_PAGE_LIMIT,
  apiAccessToken: GITHUB_API_TOKEN,
};
